<a href="https://colab.research.google.com/github/Ishanavi/ArticleRecommend3/blob/main/ProRecommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
!pip install kaggle

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (6.1.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.64.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2022.6.15)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)

In [20]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle (1).json

{'kaggle.json': b'{"username":"ishanavijain","key":"02561bb2ffdbe2c76f0b549e38baa507"}'}

In [21]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [22]:
!kaggle datasets download -d gspmoreira/articles-sharing-reading-from-cit-deskdrop

articles-sharing-reading-from-cit-deskdrop.zip: Skipping, found more recently modified local copy (use --force to force download)

In [23]:
!ls

 articles-sharing-reading-from-cit-deskdrop.zip   sample_data
'kaggle (1).json'				  shared_articles.csv
 kaggle.json					  users_interactions.csv

In [24]:
!unzip articles-sharing-reading-from-cit-deskdrop.zip

Archive:  articles-sharing-reading-from-cit-deskdrop.zip
replace shared_articles.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: shared_articles.csv
replace users_interactions.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: users_interactions.csv

In [25]:
!ls

 articles-sharing-reading-from-cit-deskdrop.zip   sample_data
'kaggle (1).json'				  shared_articles.csv
 kaggle.json					  users_interactions.csv

In [26]:
import pandas as pd
import numpy as np

df1 = pd.read_csv("shared_articles.csv")
df2 = pd.read_csv("users_interactions.csv")

df1.head()

,timestamp,eventType,contentId,authorPersonId,authorSessionId,authorUserAgent,authorRegion,authorCountry,contentType,url,title,text,lang
0,1459192779,CONTENT REMOVED,-6451309518266745024,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.nytimes.com/2016/03/28/business/dea...,"Ethereum, a Virtual Currency, Enables Transact...",All of this work is still very early. The firs...,en
1,1459193988,CONTENT SHARED,-4110354420726924665,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.nytimes.com/2016/03/28/business/dea...,"Ethereum, a Virtual Currency, Enables Transact...",All of this work is still very early. The firs...,en
2,1459194146,CONTENT SHARED,-7292285110016212249,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://cointelegraph.com/news/bitcoin-future-w...,Bitcoin Future: When GBPcoin of Branson Wins O...,The alarm clock wakes me at 8:00 with stream o...,en
3,1459194474,CONTENT SHARED,-6151852268067518688,3891637997717104548,-1457532940883382585,NaN,NaN,NaN,HTML,https://cloudplatform.googleblog.com/2016/03/G...,Google Data Center 360° Tour,We're excited to share the Google Data Center ...,en
4,1459194497,CONTENT SHARED,2448026894306402386,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,https://bitcoinmagazine.com/articles/ibm-wants...,"IBM Wants to ""Evolve the Internet"" With Blockc...",The Aite Group projects the blockchain market ...,en

In [30]:
df2.head(60)

,timestamp,eventType,contentId,personId,sessionId,userAgent,userRegion,userCountry
0,1465413032,VIEW,-3499919498720038879,-8845298781299428018,1264196770339959068,NaN,NaN,NaN
1,1465412560,VIEW,8890720798209849691,-1032019229384696495,3621737643587579081,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2...,NY,US
2,1465416190,VIEW,310515487419366995,-1130272294246983140,2631864456530402479,NaN,NaN,NaN
3,1465413895,FOLLOW,310515487419366995,344280948527967603,-3167637573980064150,NaN,NaN,NaN
4,1465412290,VIEW,-7820640624231356730,-445337111692715325,5611481178424124714,NaN,NaN,NaN
5,1465413742,VIEW,310515487419366995,-8763398617720485024,1395789369402380392,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,MG,BR
6,1465415950,VIEW,-8864073373672512525,3609194402293569455,1143207167886864524,NaN,NaN,NaN
7,1465415066,VIEW,-1492913151930215984,4254153380739593270,8743229464706506141,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,SP,BR
8,1465413762,VIEW,310515487419366995,344280948527967603,-3167637573980064150,NaN,NaN,NaN
9,1465413771,VIEW,3064370296170038610,3609194402293569455,1143207167886864524,NaN,NaN,NaN
10,1465413864,VIEW,310515487419366995,3609194402293569455,1143207167886864524,NaN,NaN,NaN
11,1465415229,VIEW,3460026829794173084,1908339160857512799,9121879357144259163,NaN,NaN,NaN
12,1465415228,VIEW,3460026829794173084,1908339160857512799,9121879357144259163,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,SP,BR
13,1465415691,VIEW,7763750328910542816,1908339160857512799,9121879357144259163,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,SP,BR
14,1465413171,VIEW,2372438485070148864,7781822014935525018,-8307903816792524795,NaN,NaN,NaN
15,1465415259,VIEW,-348408475077850711,8239286975497580612,8524822173689882396,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,SP,BR
16,1465415623,VIEW,372531153711028286,8239286975497580612,8524822173689882396,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,SP,BR
17,1465412288,VIEW,-7820640624231356730,-445337111692715325,5611481178424124714,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,MG,BR
18,1465415693,VIEW,6521856301289868251,2766187446275090740,247949759466213096,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,MG,BR
19,1465415691,VIEW,-8142426490949346803,1908339160857512799,9121879357144259163,NaN,NaN,NaN
20,1465416196,VIEW,310515487419366995,-1130272294246983140,2631864456530402479,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1...,SP,BR
21,1465415431,VIEW,7943088471380012839,8239286975497580612,8524822173689882396,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,SP,BR
22,1465415060,VIEW,-1492913151930215984,4254153380739593270,8743229464706506141,NaN,NaN,NaN
23,1465413743,VIEW,310515487419366995,-8763398617720485024,1395789369402380392,NaN,NaN,NaN
24,1465415565,VIEW,1441248639512899483,8239286975497580612,8524822173689882396,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,SP,BR
25,1465413879,BOOKMARK,310515487419366995,3609194402293569455,1143207167886864524,NaN,NaN,NaN
26,1465415695,VIEW,7763750328910542816,1908339160857512799,9121879357144259163,NaN,NaN,NaN
27,1465413954,BOOKMARK,310515487419366995,-8763398617720485024,1395789369402380392,NaN,NaN,NaN
28,1465413735,VIEW,-1492913151930215984,3609194402293569455,1143207167886864524,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,SP,BR
29,1465414324,VIEW,4306804750094230211,-1479311724257856983,5326691377159417610,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,SP,BR
30,1465413771,VIEW,3064370296170038610,3609194402293569455,1143207167886864524,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,SP,BR
31,1465413781,VIEW,1582315529508020223,3609194402293569455,1143207167886864524,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,SP,BR
32,1465413864,VIEW,310515487419366995,3609194402293569455,1143207167886864524,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,SP,BR
33,1465415756,LIKE,-8142426490949346803,1908339160857512799,9121879357144259163,NaN,NaN,NaN
34,1465413046,VIEW,-3499919498720038879,-8845298781299428018,1264196770339959068,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5...,SP,BR
35,1465415686,VIEW,6521856301289868251,2766187446275090740,247949759466213096,NaN,NaN,NaN
36,1465413867,LIKE,310515487419366995,3609194402293569455,1143207167886864524,NaN,NaN,NaN
37,1465413873,BOOKMARK,310515487419366995,344280948527967603,-3167637573980064150,NaN,NaN,NaN
38,1465415690,VIEW,-8142426490949346803,1908339160857512799,9121879357144259163,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,SP,BR
39,1465415949,VIEW,-8864073373672512525,3609194402293569455,1143207167886864524,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,SP,BR
40,1465413845,LIKE,310515487419366995,344280948527967603,-3167637573980064150,NaN,NaN,NaN
41,1465413689,VIEW,-7820640624231356730,-108842214936804958,4983461623404374015,NaN,NaN,NaN
42,1465413735,VIEW,-1492913151930215984,3609194402293569455,1143207167886864524,NaN,NaN,NaN
43,1465413946,LIKE,310515487419366995,-8763398617720485024,1395789369402380392,NaN,NaN,NaN
44,1465414478,VIEW,-1492913151930215984,7022645187549453002,-633794268364965365,NaN,NaN,NaN
45,1465413752,VIEW,-5924996404988010,6879394870211872116,4146849401428496933,NaN,NaN,NaN
46,1465414324,VIEW,4306804750094230211,-1479311724257856983,5326691377159417610,NaN,NaN,NaN
47,1465415574,VIEW,1441248639512899483,8239286975497580612,8524822173689882396,NaN,NaN,NaN
48,1465414493,VIEW,-1492913151930215984,7022645187549453002,-633794268364965365,Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKi...,RJ,BR
49,1465413751,VIEW,-5924996404988010,6879394870211872116,4146849401428496933,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,SP,BR
50,1465413689,VIEW,-7820640624231356730,-108842214936804958,4983461623404374015,Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKi...,SP,BR
51,1465413781,VIEW,1582315529508020223,3609194402293569455,1143207167886864524,NaN,NaN,NaN
52,1465413762,VIEW,310515487419366995,344280948527967603,-3167637573980064150,Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKi...,MG,BR
53,1465412561,VIEW,8890720798209849691,-1032019229384696495,3621737643587579081,NaN,NaN,NaN
54,1465413171,VIEW,2372438485070148864,7781822014935525018,-8307903816792524795,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,SP,BR
55,1465415430,VIEW,7943088471380012839,8239286975497580612,8524822173689882396,NaN,NaN,NaN
56,1465413763,LIKE,-1492913151930215984,3609194402293569455,1143207167886864524,NaN,NaN,NaN
57,1466034854,VIEW,-4205346868684833897,-1387464358334758758,5111485313337394011,Android - Native Mobile App,SP,BR
58,1466034403,VIEW,-4205346868684833897,-1387464358334758758,5111485313337394011,Android - Native Mobile App,SP,BR
59,1466033932,VIEW,7276478113479207148,3609194402293569455,-5431306901276377931,Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) ...,SP,BR

In [28]:
df1.columns

Index(['timestamp', 'eventType', 'contentId', 'authorPersonId',
       'authorSessionId', 'authorUserAgent', 'authorRegion', 'authorCountry',
       'contentType', 'url', 'title', 'text', 'lang'],
      dtype='object')

In [29]:
df1 = df1[df1['eventType']=='CONTENT SHARED']
df1.head()

,timestamp,eventType,contentId,authorPersonId,authorSessionId,authorUserAgent,authorRegion,authorCountry,contentType,url,title,text,lang
1,1459193988,CONTENT SHARED,-4110354420726924665,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.nytimes.com/2016/03/28/business/dea...,"Ethereum, a Virtual Currency, Enables Transact...",All of this work is still very early. The firs...,en
2,1459194146,CONTENT SHARED,-7292285110016212249,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://cointelegraph.com/news/bitcoin-future-w...,Bitcoin Future: When GBPcoin of Branson Wins O...,The alarm clock wakes me at 8:00 with stream o...,en
3,1459194474,CONTENT SHARED,-6151852268067518688,3891637997717104548,-1457532940883382585,NaN,NaN,NaN,HTML,https://cloudplatform.googleblog.com/2016/03/G...,Google Data Center 360° Tour,We're excited to share the Google Data Center ...,en
4,1459194497,CONTENT SHARED,2448026894306402386,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,https://bitcoinmagazine.com/articles/ibm-wants...,"IBM Wants to ""Evolve the Internet"" With Blockc...",The Aite Group projects the blockchain market ...,en
5,1459194522,CONTENT SHARED,-2826566343807132236,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.coindesk.com/ieee-blockchain-oxford...,IEEE to Talk Blockchain at Cloud Computing Oxf...,One of the largest and oldest organizations fo...,en

In [31]:
def total_events(df1_rows):
  total_likes = df2[(df2["contentId"] == df1_rows["contentId"]) & (df2['eventType'] == "LIKE")].shape[0]
  total_views = df2[(df2["contentId"] == df1_rows["contentId"]) & (df2['eventType'] == "VIEW")].shape[0]
  total_bookmarks = df2[(df2["contentId"] == df1_rows["contentId"]) & (df2['eventType'] == "BOOKMARK")].shape[0]
  total_follow = df2[(df2["contentId"] == df1_rows["contentId"]) & (df2['eventType'] == "FOLLOW")].shape[0]
  total_comments = df2[(df2["contentId"] == df1_rows["contentId"]) & (df2['eventType'] == "COMMENT CREATED")].shape[0]
  return total_likes+total_views+total_bookmarks+total_follow+total_comments

df1["total_events"] = df1.apply(total_events,axis=1)
df1.head()

,timestamp,eventType,contentId,authorPersonId,authorSessionId,authorUserAgent,authorRegion,authorCountry,contentType,url,title,text,lang,total_events
1,1459193988,CONTENT SHARED,-4110354420726924665,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.nytimes.com/2016/03/28/business/dea...,"Ethereum, a Virtual Currency, Enables Transact...",All of this work is still very early. The firs...,en,1
2,1459194146,CONTENT SHARED,-7292285110016212249,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://cointelegraph.com/news/bitcoin-future-w...,Bitcoin Future: When GBPcoin of Branson Wins O...,The alarm clock wakes me at 8:00 with stream o...,en,1
3,1459194474,CONTENT SHARED,-6151852268067518688,3891637997717104548,-1457532940883382585,NaN,NaN,NaN,HTML,https://cloudplatform.googleblog.com/2016/03/G...,Google Data Center 360° Tour,We're excited to share the Google Data Center ...,en,13
4,1459194497,CONTENT SHARED,2448026894306402386,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,https://bitcoinmagazine.com/articles/ibm-wants...,"IBM Wants to ""Evolve the Internet"" With Blockc...",The Aite Group projects the blockchain market ...,en,0
5,1459194522,CONTENT SHARED,-2826566343807132236,4340306774493623681,8940341205206233829,NaN,NaN,NaN,HTML,http://www.coindesk.com/ieee-blockchain-oxford...,IEEE to Talk Blockchain at Cloud Computing Oxf...,One of the largest and oldest organizations fo...,en,2

In [32]:
df1 = df1.sort_values(["total_events"],ascending=[False])
df1.head()

,timestamp,eventType,contentId,authorPersonId,authorSessionId,authorUserAgent,authorRegion,authorCountry,contentType,url,title,text,lang,total_events
3096,1487246811,CONTENT SHARED,-4029704725707465084,6013226412048763966,-6569695881431984742,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,SP,BR,HTML,http://www.cnbc.com/2016/12/21/former-google-c...,Former Google career coach shares a visual tri...,"If you want 2017 to be an exciting year, desig...",en,433
1671,1467813728,CONTENT SHARED,-133139342397538859,4918484843075254252,-5701227433817087697,NaN,NaN,NaN,HTML,http://gq.globo.com/Prazeres/Poder/Carreira/no...,"Novo workaholic trabalha, pratica esportes e t...",Novo workaholic não abre mão do esporte e da f...,pt,315
1814,1468867647,CONTENT SHARED,-6783772548752091658,4918484843075254252,-8995217520473210153,NaN,NaN,NaN,HTML,http://www.caroli.org/livro-retrospectivas-div...,Livro: Retrospectivas Divertidas,"Neste livro, nós fornecemos um conjunto de fer...",pt,294
1317,1465484901,CONTENT SHARED,8657408509986329668,-8020832670974472349,838596071610016700,NaN,NaN,NaN,HTML,https://medium.com/practical-blend/pull-reques...,Pull request first - Practical Blend,Pull request first After two years of working ...,en,294
588,1461629452,CONTENT SHARED,-6843047699859121724,7527226129639571966,-1297230017812472163,NaN,NaN,NaN,HTML,https://medium.com/@jeffersoncn/ganhe-6-meses-...,"Ganhe 6 meses de acesso ao Pluralsight, maior ...","Ganhe 6 meses de acesso ao Pluralsight, maior ...",pt,281

In [33]:
def convert_to_lowercase(x):
  if isinstance(x,str):
    return x.lower()
  else:
    return ""

df1["title"] = df1["title"].apply(convert_to_lowercase)
df1.head()

,timestamp,eventType,contentId,authorPersonId,authorSessionId,authorUserAgent,authorRegion,authorCountry,contentType,url,title,text,lang,total_events
3096,1487246811,CONTENT SHARED,-4029704725707465084,6013226412048763966,-6569695881431984742,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,SP,BR,HTML,http://www.cnbc.com/2016/12/21/former-google-c...,former google career coach shares a visual tri...,"If you want 2017 to be an exciting year, desig...",en,433
1671,1467813728,CONTENT SHARED,-133139342397538859,4918484843075254252,-5701227433817087697,NaN,NaN,NaN,HTML,http://gq.globo.com/Prazeres/Poder/Carreira/no...,"novo workaholic trabalha, pratica esportes e t...",Novo workaholic não abre mão do esporte e da f...,pt,315
1814,1468867647,CONTENT SHARED,-6783772548752091658,4918484843075254252,-8995217520473210153,NaN,NaN,NaN,HTML,http://www.caroli.org/livro-retrospectivas-div...,livro: retrospectivas divertidas,"Neste livro, nós fornecemos um conjunto de fer...",pt,294
1317,1465484901,CONTENT SHARED,8657408509986329668,-8020832670974472349,838596071610016700,NaN,NaN,NaN,HTML,https://medium.com/practical-blend/pull-reques...,pull request first - practical blend,Pull request first After two years of working ...,en,294
588,1461629452,CONTENT SHARED,-6843047699859121724,7527226129639571966,-1297230017812472163,NaN,NaN,NaN,HTML,https://medium.com/@jeffersoncn/ganhe-6-meses-...,"ganhe 6 meses de acesso ao pluralsight, maior ...","Ganhe 6 meses de acesso ao Pluralsight, maior ...",pt,281

In [34]:
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(df1['title'])

from sklearn.metrics.pairwise import cosine_similarity

cosine_sim_2 = cosine_similarity(count_matrix, count_matrix)

df1 = df1.reset_index()
indices = pd.Series(df1.index, index=df1['contentId'])

In [35]:
def get_recommendations(contentId, cosine_sim):
    idx = indices[contentId]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    article_indices = [i[0] for i in sim_scores]
    return df1['contentId'].iloc[article_indices]

In [37]:
get_recommendations(-6783772548752091658, cosine_sim_2)

811    -3417523159811412977
2677   -1669098707776725430
0      -4029704725707465084
1       -133139342397538859
3       8657408509986329668
4      -6843047699859121724
5      -2358756719610361882
6      -8208801367848627943
7       2581138407738454418
8      -1297580205670251233
Name: contentId, dtype: int64